//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FontendResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FontendResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FontendResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        internal static string aboutme {
            get {
                return ResourceManager.GetString("aboutme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been created successfully!.
        /// </summary>
        internal static string accounthasbeencreatedsuccessfully {
            get {
                return ResourceManager.GetString("accounthasbeencreatedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not exist.
        /// </summary>
        internal static string accountisnotexist {
            get {
                return ResourceManager.GetString("accountisnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Management.
        /// </summary>
        internal static string accountmanagement {
            get {
                return ResourceManager.GetString("accountmanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account recovery email sent to.
        /// </summary>
        internal static string accountrecoveryemailsentto {
            get {
                return ResourceManager.GetString("accountrecoveryemailsentto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Caption.
        /// </summary>
        internal static string addcaption {
            get {
                return ResourceManager.GetString("addcaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to cart.
        /// </summary>
        internal static string addedtocart {
            get {
                return ResourceManager.GetString("addedtocart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address to shipping.
        /// </summary>
        internal static string addresstoshipping {
            get {
                return ResourceManager.GetString("addresstoshipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        internal static string addtocart {
            get {
                return ResourceManager.GetString("addtocart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture Orders.
        /// </summary>
        internal static string architectureorders {
            get {
                return ResourceManager.GetString("architectureorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Payment.
        /// </summary>
        internal static string awaitingpayment {
            get {
                return ResourceManager.GetString("awaitingpayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Info.
        /// </summary>
        internal static string basicinfo {
            get {
                return ResourceManager.GetString("basicinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below are our service packages. You can choose a package that is right for you.
        /// </summary>
        internal static string belowareourservicepackagesyoucanchooseapackagethatisrightforyou {
            get {
                return ResourceManager.GetString("belowareourservicepackagesyoucanchooseapackagethatisrightforyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        internal static string birthdate {
            get {
                return ResourceManager.GetString("birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Place.
        /// </summary>
        internal static string birthplace {
            get {
                return ResourceManager.GetString("birthplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call us.
        /// </summary>
        internal static string callus {
            get {
                return ResourceManager.GetString("callus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel failed.
        /// </summary>
        internal static string cancelfailed {
            get {
                return ResourceManager.GetString("cancelfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string cancelled {
            get {
                return ResourceManager.GetString("cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel successfully!.
        /// </summary>
        internal static string cancelsuccessfully {
            get {
                return ResourceManager.GetString("cancelsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cart.
        /// </summary>
        internal static string cart {
            get {
                return ResourceManager.GetString("cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi thành công.
        /// </summary>
        internal static string changesucceeded {
            get {
                return ResourceManager.GetString("changesucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        internal static string checkout {
            get {
                return ResourceManager.GetString("checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn một mật khẩu mới..
        /// </summary>
        internal static string chooseanewpassword {
            get {
                return ResourceManager.GetString("chooseanewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click vào đây để tải chúng.
        /// </summary>
        internal static string clickheretodownloadthem {
            get {
                return ResourceManager.GetString("clickheretodownloadthem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click vào đây để xem thêm.
        /// </summary>
        internal static string clickheretoseethem {
            get {
                return ResourceManager.GetString("clickheretoseethem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click để cập nhật.
        /// </summary>
        internal static string clicktoupdate {
            get {
                return ResourceManager.GetString("clicktoupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu sắc.
        /// </summary>
        internal static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều kiện.
        /// </summary>
        internal static string condition {
            get {
                return ResourceManager.GetString("condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xác nhận thanh toán.
        /// </summary>
        internal static string confirmedpayment {
            get {
                return ResourceManager.GetString("confirmedpayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục mua hàng.
        /// </summary>
        internal static string continueshopping {
            get {
                return ResourceManager.GetString("continueshopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string ddmmyyyy {
            get {
                return ResourceManager.GetString("ddmmyyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        internal static string deletedsuccessfully {
            get {
                return ResourceManager.GetString("deletedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã giao hàng.
        /// </summary>
        internal static string delivered {
            get {
                return ResourceManager.GetString("delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thiết kế..
        /// </summary>
        internal static string designno {
            get {
                return ResourceManager.GetString("designno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt thiết kế.
        /// </summary>
        internal static string designorders {
            get {
                return ResourceManager.GetString("designorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phong cách thiết kế đã chọn.
        /// </summary>
        internal static string designstyleselected {
            get {
                return ResourceManager.GetString("designstyleselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem chi tiết.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XProject.com.
        /// </summary>
        internal static string domain {
            get {
                return ResourceManager.GetString("domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to domainname.
        /// </summary>
        internal static string domainname {
            get {
                return ResourceManager.GetString("domainname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://XProject.com/.
        /// </summary>
        internal static string domainroot {
            get {
                return ResourceManager.GetString("domainroot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải thiết kế.
        /// </summary>
        internal static string downloaddesign {
            get {
                return ResourceManager.GetString("downloaddesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link tải sách.
        /// </summary>
        internal static string downloadgift {
            get {
                return ResourceManager.GetString("downloadgift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn hủy đơn hàng này không?.
        /// </summary>
        internal static string doyouwanttocancelthisorder {
            get {
                return ResourceManager.GetString("doyouwanttocancelthisorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Email bắt buộc.
        /// </summary>
        internal static string emailaddessmustnotbeempty {
            get {
                return ResourceManager.GetString("emailaddessmustnotbeempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Email address sentered is invalid..
        /// </summary>
        internal static string emailaddressenteredisinvalid {
            get {
                return ResourceManager.GetString("emailaddressenteredisinvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Email đang được sử dụng. Vui lòng đăng nhập.
        /// </summary>
        internal static string emailisinuseplsloginwiththisemail {
            get {
                return ResourceManager.GetString("emailisinuseplsloginwiththisemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email chưa được sử dụng.
        /// </summary>
        internal static string emailisnotinuser {
            get {
                return ResourceManager.GetString("emailisnotinuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt lại mật khẩu.
        /// </summary>
        internal static string email_subject_forgetpassword {
            get {
                return ResourceManager.GetString("email_subject_forgetpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi sẽ sớm liện lạc với bạn để xác nhận đơn hàng..
        /// </summary>
        internal static string email_subject_newcustomer {
            get {
                return ResourceManager.GetString("email_subject_newcustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng #{0} đã hoàn tất. {1}.
        /// </summary>
        internal static string email_subject_orderdelivery {
            get {
                return ResourceManager.GetString("email_subject_orderdelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng #{0} đang gia công..
        /// </summary>
        internal static string email_subject_orderprocessing {
            get {
                return ResourceManager.GetString("email_subject_orderprocessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tặng phẩm từ công ty tư vấn kiến trúc Duy Thành.
        /// </summary>
        internal static string email_subject_subscribe_gift {
            get {
                return ResourceManager.GetString("email_subject_subscribe_gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm....
        /// </summary>
        internal static string entersearchtext {
            get {
                return ResourceManager.GetString("entersearchtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPERIENCE.
        /// </summary>
        internal static string experience {
            get {
                return ResourceManager.GetString("experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã lỗi! Vui lòng thử lại lần nữa..
        /// </summary>
        internal static string failedplstryagain {
            get {
                return ResourceManager.GetString("failedplstryagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu sắc yêu thích.
        /// </summary>
        internal static string favoritescolor {
            get {
                return ResourceManager.GetString("favoritescolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh yêu thích.
        /// </summary>
        internal static string favoritesimage {
            get {
                return ResourceManager.GetString("favoritesimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không gian yêu thích.
        /// </summary>
        internal static string favoritesspace {
            get {
                return ResourceManager.GetString("favoritesspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feng Shui.
        /// </summary>
        internal static string fengshui {
            get {
                return ResourceManager.GetString("fengshui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin.
        /// </summary>
        internal static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hoàn thành.
        /// </summary>
        internal static string finished {
            get {
                return ResourceManager.GetString("finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mềm dẻo.
        /// </summary>
        internal static string flexibility {
            get {
                return ResourceManager.GetString("flexibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        internal static string forgetpassword {
            get {
                return ResourceManager.GetString("forgetpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu?.
        /// </summary>
        internal static string forgotpassword {
            get {
                return ResourceManager.GetString("forgotpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập địa chỉ email và chúng tôi sẽ gửi bạn đường dẫn để khôi phục mật khẩu thông qua email..
        /// </summary>
        internal static string forgotyouraccountpassword {
            get {
                return ResourceManager.GetString("forgotyouraccountpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cho thanh toán của bạn.
        /// </summary>
        internal static string foryourpaymentof {
            get {
                return ResourceManager.GetString("foryourpaymentof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội Thất.
        /// </summary>
        internal static string furniture {
            get {
                return ResourceManager.GetString("furniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem album.
        /// </summary>
        internal static string galleryview {
            get {
                return ResourceManager.GetString("galleryview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        internal static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đi đến trang chủ.
        /// </summary>
        internal static string gotohomepage {
            get {
                return ResourceManager.GetString("gotohomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đi đến trang quản lý đơn hàng.
        /// </summary>
        internal static string gotoordermanagement {
            get {
                return ResourceManager.GetString("gotoordermanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuế.
        /// </summary>
        internal static string gst {
            get {
                return ResourceManager.GetString("gst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot line.
        /// </summary>
        internal static string hotnumber {
            get {
                return ResourceManager.GetString("hotnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        internal static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email hoặc mật khẩu không đúng.
        /// </summary>
        internal static string invalidemailorpassword {
            get {
                return ResourceManager.GetString("invalidemailorpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghề nghiệp.
        /// </summary>
        internal static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tham gia.
        /// </summary>
        internal static string joined {
            get {
                return ResourceManager.GetString("joined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhỏ hơn.
        /// </summary>
        internal static string lessthan {
            get {
                return ResourceManager.GetString("lessthan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made In.
        /// </summary>
        internal static string madein {
            get {
                return ResourceManager.GetString("madein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string mailus {
            get {
                return ResourceManager.GetString("mailus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vật chất.
        /// </summary>
        internal static string material {
            get {
                return ResourceManager.GetString("material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải lên tối đa.
        /// </summary>
        internal static string maxupload {
            get {
                return ResourceManager.GetString("maxupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin thêm.
        /// </summary>
        internal static string moreinfo {
            get {
                return ResourceManager.GetString("moreinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mới.
        /// </summary>
        internal static string new1 {
            get {
                return ResourceManager.GetString("new1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        internal static string newpassword {
            get {
                return ResourceManager.GetString("newpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ.
        /// </summary>
        internal static string oldpassword {
            get {
                return ResourceManager.GetString("oldpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng.
        /// </summary>
        internal static string oldpasswordisnotmatch {
            get {
                return ResourceManager.GetString("oldpasswordisnotmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oooops, thanh toán không tồn tại....
        /// </summary>
        internal static string oooopspaymentisnotexist {
            get {
                return ResourceManager.GetString("oooopspaymentisnotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oooops, something went wrong....
        /// </summary>
        internal static string oooopssomethingwentwrong {
            get {
                return ResourceManager.GetString("oooopssomethingwentwrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đi đến cửa hàng.
        /// </summary>
        internal static string openstore {
            get {
                return ResourceManager.GetString("openstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đặt hàng.
        /// </summary>
        internal static string orderdate {
            get {
                return ResourceManager.GetString("orderdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã đặt hàng.
        /// </summary>
        internal static string ordered {
            get {
                return ResourceManager.GetString("ordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn hàng..
        /// </summary>
        internal static string orderno {
            get {
                return ResourceManager.GetString("orderno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng không tồn tại.
        /// </summary>
        internal static string ordernotfound {
            get {
                return ResourceManager.GetString("ordernotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng ngay.
        /// </summary>
        internal static string ordernow {
            get {
                return ResourceManager.GetString("ordernow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn hàng.
        /// </summary>
        internal static string ordernumber {
            get {
                return ResourceManager.GetString("ordernumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng thành công!.
        /// </summary>
        internal static string ordersucceeded {
            get {
                return ResourceManager.GetString("ordersucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi cung cấp cho bạn mật khẩu vào hệ thống thông qua email.
        /// </summary>
        internal static string ordersucceededfornewcustomer {
            get {
                return ResourceManager.GetString("ordersucceededfornewcustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi đã nhận đươc yêu cầu tư vấn thiết kế, chúng tôi sẽ liên hệ bạn trong thời gian sớm nhất..
        /// </summary>
        internal static string ordersucceededtextlong {
            get {
                return ResourceManager.GetString("ordersucceededtextlong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên lạc của chúng tôi.
        /// </summary>
        internal static string ourcontactinfo {
            get {
                return ResourceManager.GetString("ourcontactinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các kênh xã hội của chúng tôi.
        /// </summary>
        internal static string oursocialchannels {
            get {
                return ResourceManager.GetString("oursocialchannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy nội dung.
        /// </summary>
        internal static string pagenotfound {
            get {
                return ResourceManager.GetString("pagenotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không đúng.
        /// </summary>
        internal static string passwordisnotcorrect {
            get {
                return ResourceManager.GetString("passwordisnotcorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Mật khẩu phải là chuổi nhiều hơn 6 ký tự.
        /// </summary>
        internal static string passwordmustbeastringaminimumlengthof6 {
            get {
                return ResourceManager.GetString("passwordmustbeastringaminimumlengthof6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức thanh toán.
        /// </summary>
        internal static string paymentmethod {
            get {
                return ResourceManager.GetString("paymentmethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang chờ xử lý.
        /// </summary>
        internal static string pending {
            get {
                return ResourceManager.GetString("pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot line.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng thêm thông tin dưới đây để chúng tôi có thể phục vụ bạn tốt nhất..
        /// </summary>
        internal static string plsaddtheinfobelowsowecanbestserveyou {
            get {
                return ResourceManager.GetString("plsaddtheinfobelowsowecanbestserveyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra email của bạn và click vào liên kết an toàn..
        /// </summary>
        internal static string plscheckyouremailandclickthesecurelink {
            get {
                return ResourceManager.GetString("plscheckyouremailandclickthesecurelink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a password to continue join us..
        /// </summary>
        internal static string plschooseapasswordtocontinuejoinus {
            get {
                return ResourceManager.GetString("plschooseapasswordtocontinuejoinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một gói dịch vụ ở trên.
        /// </summary>
        internal static string plsselectaservicepackageabove {
            get {
                return ResourceManager.GetString("plsselectaservicepackageabove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng cập nhật thông tin tài khoản của bạn để chúng tôi có thể phục vụ bạn tốt nhất..
        /// </summary>
        internal static string plsupdateyouraccountinfosowecanbestserveyou {
            get {
                return ResourceManager.GetString("plsupdateyouraccountinfosowecanbestserveyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTFOLIO.
        /// </summary>
        internal static string portfolio {
            get {
                return ResourceManager.GetString("portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý.
        /// </summary>
        internal static string processing {
            get {
                return ResourceManager.GetString("processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết sản phẩm.
        /// </summary>
        internal static string productdescription {
            get {
                return ResourceManager.GetString("productdescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        internal static string productname {
            get {
                return ResourceManager.GetString("productname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm.
        /// </summary>
        internal static string productno {
            get {
                return ResourceManager.GetString("productno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua gói dịch vụ này.
        /// </summary>
        internal static string purchasethispackage {
            get {
                return ResourceManager.GetString("purchasethispackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề xuất địa điểm.
        /// </summary>
        internal static string recommendplace {
            get {
                return ResourceManager.GetString("recommendplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string rememberme {
            get {
                return ResourceManager.GetString("rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Required.
        /// </summary>
        internal static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires upload least 1 image.
        /// </summary>
        internal static string requiresuploadleast1image {
            get {
                return ResourceManager.GetString("requiresuploadleast1image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require verify email.
        /// </summary>
        internal static string requireverifyemail {
            get {
                return ResourceManager.GetString("requireverifyemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string resetpassword {
            get {
                return ResourceManager.GetString("resetpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        internal static string resetyourpassword {
            get {
                return ResourceManager.GetString("resetyourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu mới.
        /// </summary>
        internal static string retypenewpassword {
            get {
                return ResourceManager.GetString("retypenewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu.
        /// </summary>
        internal static string retypepassword {
            get {
                return ResourceManager.GetString("retypepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Mật khẩu nhập lại không trùng khớp.
        /// </summary>
        internal static string retypepasswordandpassworddonotmatch {
            get {
                return ResourceManager.GetString("retypepasswordandpassworddonotmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thay đổi.
        /// </summary>
        internal static string savechanges {
            get {
                return ResourceManager.GetString("savechanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu đã thành công.
        /// </summary>
        internal static string savesucceeded {
            get {
                return ResourceManager.GetString("savesucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thành công.
        /// </summary>
        internal static string savesuccessfully {
            get {
                return ResourceManager.GetString("savesuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn nơi sinh.
        /// </summary>
        internal static string selectbirthplace {
            get {
                return ResourceManager.GetString("selectbirthplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn màu.
        /// </summary>
        internal static string selectcolor {
            get {
                return ResourceManager.GetString("selectcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn nơi ở.
        /// </summary>
        internal static string selectplace {
            get {
                return ResourceManager.GetString("selectplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi Email khôi phục.
        /// </summary>
        internal static string sendrecoveryemail {
            get {
                return ResourceManager.GetString("sendrecoveryemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gói dịch vụ.
        /// </summary>
        internal static string servicepackage {
            get {
                return ResourceManager.GetString("servicepackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Những gói dịch vụ.
        /// </summary>
        internal static string servicepackages {
            get {
                return ResourceManager.GetString("servicepackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gói dịch vụ đã chọn.
        /// </summary>
        internal static string servicepackageselected {
            get {
                return ResourceManager.GetString("servicepackageselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVICES.
        /// </summary>
        internal static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ giao hàng.
        /// </summary>
        internal static string shipaddess {
            get {
                return ResourceManager.GetString("shipaddess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ giao hàng và hình thức thanh toán.
        /// </summary>
        internal static string shippingpaymentmethod {
            get {
                return ResourceManager.GetString("shippingpaymentmethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng.
        /// </summary>
        internal static string shopcart {
            get {
                return ResourceManager.GetString("shopcart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký tài khoản.
        /// </summary>
        internal static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký tài khoản để theo dõi đơn hàng của bạn..
        /// </summary>
        internal static string signuptogetfullaccessandtrackyourorders {
            get {
                return ResourceManager.GetString("signuptogetfullaccessandtrackyourorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm tương tự.
        /// </summary>
        internal static string similaritems {
            get {
                return ResourceManager.GetString("similaritems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website đang được bảo trì.
        /// </summary>
        internal static string siteismaintenance {
            get {
                return ResourceManager.GetString("siteismaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước.
        /// </summary>
        internal static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin lỗi bạn.
        /// </summary>
        internal static string sorry {
            get {
                return ResourceManager.GetString("sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặc điểm kỹ thuật.
        /// </summary>
        internal static string specification {
            get {
                return ResourceManager.GetString("specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cửa hàng.
        /// </summary>
        internal static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phong cách.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phong cách không tồn tại.
        /// </summary>
        internal static string stylenotfound {
            get {
                return ResourceManager.GetString("stylenotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận Thay đổi.
        /// </summary>
        internal static string submitchange {
            get {
                return ResourceManager.GetString("submitchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận đặt hàng.
        /// </summary>
        internal static string submitorder {
            get {
                return ResourceManager.GetString("submitorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng phụ.
        /// </summary>
        internal static string subtotal {
            get {
                return ResourceManager.GetString("subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MST.
        /// </summary>
        internal static string taxnumber {
            get {
                return ResourceManager.GetString("taxnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEAM.
        /// </summary>
        internal static string team {
            get {
                return ResourceManager.GetString("team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn bạn.
        /// </summary>
        internal static string thankyou {
            get {
                return ResourceManager.GetString("thankyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn bạn đã đăng ký với Duy Thành!.
        /// </summary>
        internal static string thankyouforsubscribe {
            get {
                return ResourceManager.GetString("thankyouforsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra sự cố khi xử lý yêu cầu của bạn. Vui lòng thử lại..
        /// </summary>
        internal static string therewasaproblemprocessingyourrequest {
            get {
                return ResourceManager.GetString("therewasaproblemprocessingyourrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đây là mật khẩu của bạn để đăng nhập vào hệ thống. Bạn có thể xem trạng thái đơn hàng thông qua hệ thống..
        /// </summary>
        internal static string thisisyourpasswordtoaccessmysystem {
            get {
                return ResourceManager.GetString("thisisyourpasswordtoaccessmysystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng giá sau thuế.
        /// </summary>
        internal static string totalpriceaftergst {
            get {
                return ResourceManager.GetString("totalpriceaftergst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng giá trước thuế.
        /// </summary>
        internal static string totalpricebeforegst {
            get {
                return ResourceManager.GetString("totalpricebeforegst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch thất bại!.
        /// </summary>
        internal static string transactionfailed {
            get {
                return ResourceManager.GetString("transactionfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá.
        /// </summary>
        internal static string unitprice {
            get {
                return ResourceManager.GetString("unitprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận email.
        /// </summary>
        internal static string verifyemail {
            get {
                return ResourceManager.GetString("verifyemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phiên bản.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to webaddress.
        /// </summary>
        internal static string webaddress {
            get {
                return ResourceManager.GetString("webaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to webemail.
        /// </summary>
        internal static string webemail {
            get {
                return ResourceManager.GetString("webemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to webphone.
        /// </summary>
        internal static string webphone {
            get {
                return ResourceManager.GetString("webphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi có các sản phẩm tương tự hiện có trong kho.
        /// </summary>
        internal static string wehavesimilarproductscurrentlyinstock {
            get {
                return ResourceManager.GetString("wehavesimilarproductscurrentlyinstock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rất tiếc....
        /// </summary>
        internal static string wellshucks {
            get {
                return ResourceManager.GetString("wellshucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi sẽ quay lại ngay.
        /// </summary>
        internal static string wewillbebackshortly {
            get {
                return ResourceManager.GetString("wewillbebackshortly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi sẽ thiết kế cho bạn sớm..
        /// </summary>
        internal static string wewilldesignforyousoon {
            get {
                return ResourceManager.GetString("wewilldesignforyousoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi sẽ bắt đầu thiết kế cho đơn hàng của bạn sớm.
        /// </summary>
        internal static string wewillstartdesingingforyousoon {
            get {
                return ResourceManager.GetString("wewillstartdesingingforyousoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn hiện đang đăng nhập ở một nơi khác. Vui lòng thử lại sau!.
        /// </summary>
        internal static string youraccountiscurrentlylogged {
            get {
                return ResourceManager.GetString("youraccountiscurrentlylogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh thực của căn hộ bạn.
        /// </summary>
        internal static string youractualimages {
            get {
                return ResourceManager.GetString("youractualimages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng #{0} đang gia công..
        /// </summary>
        internal static string yourorderisprocessing {
            get {
                return ResourceManager.GetString("yourorderisprocessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu của bạn.
        /// </summary>
        internal static string yourpassword {
            get {
                return ResourceManager.GetString("yourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu của bạn đã thay đổi thành công!.
        /// </summary>
        internal static string yourpasswordhasbeenchangedsuccessfully {
            get {
                return ResourceManager.GetString("yourpasswordhasbeenchangedsuccessfully", resourceCulture);
            }
        }
    }
}
